Repository mineadmin/MineAdmin-Vue, pull requests merged in 2024-06, with the labels that each got.

#178 操作按钮自定义颜色
  src/components/ma-crud/components/column.vue
Labels: enhancement, size:XS, lgtm

#183 fix:修复ma-curd行选择器的bug
  src/components/ma-crud/index.vue
Labels: bug, size:XS

#180 Update form-input.vue
  src/components/ma-crud/components/searchFormItem/form-input.vue
Labels: bug, size:XS

#182 增加maFormRef
  src/components/ma-form/index.vue
Labels: enhancement, size:XS

#179 Update index.vue
  src/components/ma-info/index.vue
Labels: size:XS, lgtm

#173 fix: 修改ma-crud columns types的类型拼写错误
  src/components/ma-crud/types/columns.ts
Labels: bug, size:XS, lgtm

#186 Remove default env file and generating by postinstall
  .env.example
  .gitignore
  package.json
  scripts/postinstall.js
Labels: enhancement, size:S

#187 Update form-tree-select.vue
  src/components/ma-form/formItem/form-tree-select.vue
Labels: bug, size:XS

#190 feat(ma-editor): Added Image Upload
  src/components/ma-editor/index.vue
Labels: enhancement, size:S, lgtm
