Repository mineadmin/MineAdmin-Vue, pull requests merged in 2024-07, with the labels that each got.

#194 fix: 修复菜单编辑选择图标未能清除问题
  src/components/ma-icon/index.vue
Labels: bug, size:S, lgtm

#197 fix(crud): 修复middleContent插槽导致页面高度异常
  src/components/ma-crud/index.vue
Labels: bug, size:XS

#196 fix(dict): Optimized dictionary loading and synchronization of pagina…
  src/components/ma-crud/components/searchFormItem/form-select.vue
  src/components/ma-form/formItem/form-select.vue
  src/views/setting/config/index.vue
Labels: bug, size:S, lgtm

#199 feat(crud): 添加最小列宽支持
  src/components/ma-crud/components/column.vue
  src/components/ma-crud/index.vue
  src/components/ma-crud/js/defaultOptions.js
Labels: enhancement, size:XS

#198 fix(ma-resource): prevent image component from throwing error when sr…
  src/components/ma-resource/index.vue
Labels: bug, size:XS, lgtm

#201 feat: ma-crud 暴露 setTableData 方法
  src/components/ma-crud/index.vue
Labels: enhancement, size:XS, lgtm

#200 Added component to FormDataType
  src/components/ma-crud/types/columns.ts
Labels: enhancement, size:XS

#202 feat(form-select): add select all and clear features for multiple selections
  src/components/ma-crud/components/searchFormItem/form-select.vue
Labels: bug, enhancement, size:L, lgtm
